---
labels:
  platform: linux/amd64
  backend: docker

when:
  event:
    - tag

depends_on:
  - linux-build-and-push
  - windows-build-and-push

matrix:
  plugin:
    - teams-notify

steps:
  - name: add manifest Windows/Linux
    image: ${DOCKER_INTERNAL_REGISTRY}/docker-hub/docker:28-cli
    environment:
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
      DOCKER_USERNAME:
        from_secret: DOCKER_REGISTRY_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_REGISTRY_PASSWORD
    commands:
      - echo "Create docker manifest for windows and linux image..."
      - echo $${DOCKER_PASSWORD} | docker login --username $${DOCKER_USERNAME} --password-stdin $${DOCKER_REGISTRY}
      - docker manifest create $${DOCKER_REGISTRY}/${CI_REPO_OWNER,,}/woodpecker-${plugin}-plugin:latest
                        --amend $${DOCKER_REGISTRY}/${CI_REPO_OWNER,,}/woodpecker-${plugin}-plugin:windows-ltsc2022-amd64
                        --amend $${DOCKER_REGISTRY}/${CI_REPO_OWNER,,}/woodpecker-${plugin}-plugin:linux-amd64
                        --amend $${DOCKER_REGISTRY}/${CI_REPO_OWNER,,}/woodpecker-${plugin}-plugin:linux-arm64
      - docker manifest push --purge $${DOCKER_REGISTRY}/${CI_REPO_OWNER,,}/woodpecker-${plugin}-plugin:latest
