---
labels:
  platform: linux/amd64
  backend: docker

when:
  event:
    - tag

depends_on:
  - linux-build-and-push
  - windows-build-and-push

skip_clone: true

matrix:
  include:
    - image: woodpecker-teams-notify-plugin
      version: latest
    - image: woodpecker-teams-notify-plugin
      version: ${CI_COMMIT_TAG}-linux-amd64
    - image: woodpecker-teams-notify-plugin
      version: ${CI_COMMIT_TAG}-linux-arm64
    - image: woodpecker-teams-notify-plugin
      version: ${CI_COMMIT_TAG}-ltsc2022

steps:
  - name: Add 'docker-hub' label
    image: ${DOCKER_INTERNAL_REGISTRY}/${CI_REPO_OWNER,,}/woodpecker-harbor-label-plugin
    pull: true
    settings:
      registry:
        from_secret: DOCKER_REGISTRY
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASSWORD
      debug: true
      label: docker-hub
      project: ${CI_REPO_OWNER,,}
      image: ${image}
      tag: ${version}
