---
labels:
  platform: linux/amd64
  backend: docker

when:
  event:
    - tag

depends_on:
  - docker-manifest

skip_clone: true

matrix:
  plugin:
    - teams-notify
  version:
    - latest
    - linux-amd64
    - linux-arm64
    - windows-ltsc2022-amd64

steps:
  - name: Add 'docker-hub' label
    image: ${DOCKER_INTERNAL_REGISTRY}/${CI_REPO_OWNER,,}/woodpecker-harbor-label-plugin
    pull: true
    settings:
      registry:
        from_secret: DOCKER_REGISTRY
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASSWORD
      debug: true
      label: docker-hub
      project: ${CI_REPO_OWNER,,}
      image: woodpecker-${plugin}-plugin
      tag: ${version}
