---
labels:
  platform: windows/amd64
  backend: local

depends_on:
  - lint

matrix:
  plugin:
    - teams-notify

steps:
  - name: build
    image: bash.exe
    environment:
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
    commands:
      - docker build --file Dockerfile.Windows
                     --build-arg="DOCKER_REGISTRY=$${DOCKER_REGISTRY}/${CI_REPO_OWNER,,}"
                     --tag $${DOCKER_REGISTRY}/${CI_REPO_OWNER,,}/woodpecker-${plugin}-plugin:${CI_COMMIT_SHA:0:10}-ltsc2022 .
    when:
      event: [tag, push]

  - name: push
    image: bash.exe
    environment:
      DOCKER_REGISTRY:
        from_secret: DOCKER_REGISTRY
      DOCKER_REGISTRY_USERNAME:
        from_secret: DOCKER_REGISTRY_USERNAME
      DOCKER_REGISTRY_PASSWORD:
        from_secret: DOCKER_REGISTRY_PASSWORD
    commands:
      - echo "$${DOCKER_REGISTRY_PASSWORD}" | docker login $${DOCKER_REGISTRY} --username $${DOCKER_REGISTRY_USERNAME} --password-stdin
      - docker image tag $${DOCKER_REGISTRY}/${CI_REPO_OWNER,,}/woodpecker-${plugin}-plugin:${CI_COMMIT_SHA:0:10}-ltsc2022
                         $${DOCKER_REGISTRY}/${CI_REPO_OWNER,,}/woodpecker-${plugin}-plugin:${CI_COMMIT_TAG}-ltsc2022
      - docker push $${DOCKER_REGISTRY}/${CI_REPO_OWNER,,}/woodpecker-${plugin}-plugin:${CI_COMMIT_TAG}-ltsc2022
    when:
      event: tag

  - name: clean
    image: bash.exe
    commands:
      - echo "Remove all stopped containers..."
      - docker rm $(docker ps --filter "status=exited" -q) 2> /dev/null || true
      - echo "Remove all unused images..."
      - docker image rm $(docker images --filter "dangling=true" -q --no-trunc) 2> /dev/null || true
      - echo "Remove Woodpecker volumes..."
      - docker volume rm $(docker volume ls --filter name=^wp_* --filter dangling=true  -q) 2> /dev/null || true
    when:
      event: [push, tag]
